---
version: "3.2"
services:
  potos-iso-creation:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POTOS_FULL_DISK_ENCRYPTION_INITIAL_PASSWORD: ${POTOS_FULL_DISK_ENCRYPTION_INITIAL_PASSWORD}
        POTOS_INITIAL_HOSTNAME: ${POTOS_INITIAL_HOSTNAME}
        POTOS_CLIENT_NAME: ${POTOS_CLIENT_NAME}
    volumes:
      - type: bind
        source: ./potos-images
        target: /potos-iso/potos-images
    env_file: .env
